### ISSUE TITLE
big_univLinReg() slow when subsetting rows/cols

### ISSUE THREAD

**Issue by linoferreira** [privefl/bigstatsr#138]
I'm using `big_univLinReg()` to run univariate linear regressions of a continuous variable on a `bigSNP` object with imputed dosages. I want to run these regressions on a subset of the `bigSNP` object (only some rows and columns) and I've found that using `ind.train` and `ind.col` slows things down significantly compared to subsetting the `bigSNP` object into the desired rows/columns with `bigsnpr::snp_subset()` and running `big_univLinReg()` on that smaller `bigSNP` object (using all rows/columns). I wanted to ask if this is expected behaviour or if there's something I could do to increase speed.

Here's a concrete example: I have a `bigSNP` object on disk with approximately 900,000 columns (these are SNPs with imputed dosages from the UK Biobank) and 485,000 rows (samples). I would like to do a sort of GWAS where I regress a continuous variable on approximately 40,000 SNPs in a training sample of approximately 340,000 people.

Since I have this large `bigSNP` object on disk containing all the predictors I need, I think the easiest way to do this would be:

    # load dosages
    geno <- bigsnpr::snp_attach("chr1.rds")

    # run regressions
    linreg <- big_univLinReg(geno[[chr]]$genotypes,
                                  phen,
                                  ind.train = train_sp_ind,
                                  ind.col = snp_id_ind,
                                  ncores = nb_cores())

where `phen` is a length-340,000 vector, `train_sp_ind` is a vector of the row indices corresponding to the samples I want to include and `snp_id_ind` is a vector of the column indices corresponding to the SNPs I want to consider. I'm running this on an HPC cluster and using 4 cores, so `nb_cores() = 3`. This takes approximately 450 seconds to run.

Alternatively, I've tried subsetting the `bigSNP` object into exactly the rows/columns I need and then running `big_univLinReg`:

    # subset bigSNP
    geno_train_rds <- bigsnpr::snp_subset(geno,
                                                 ind.row = train_sp_ind,
                                                 ind.col = snp_id_ind,
                                                 backingfile = "chr1-train")

    # load smaller X matrix with dosages
    geno_train <- bigsnpr::snp_attach(geno_train_rds)

    # run regressions
    linreg <- big_univLinReg(geno_train$genotypes,
                                  phen,
                                  ncores = nb_cores())

Here the call to `big_univLinReg` takes only 17 seconds!

I'll be running many similar regressions with different phenotypes on the same X matrix and so wanted it to be as fast as possible. Given what I have at the moment it's faster to subset the `bigSNP` object but this takes more space on disk, so I was wondering if it's expected that using `ind.train` and `ind.col` slow down the regressions so much and if there's anything I could do about it.

Thank you very much for your time!

**Comment by privefl** [comment]
There are two things to consider. 
The first one is, when you access some data for the very first time, this is accessed from disk. But, the second time and later, this is accessed from RAM instead, which is much faster.
The second one is the actual computation time once the data is accessed, which should be very fast for `big_univLinReg()`.

What I think happens here is that it needs to read all the 40,000 columns once from disk and then do the computation (maybe 450 seconds).
When you write a subset and use it directly, this is already in cache (if enough memory) and is therefore accessible directly very fast (17 sec). But I guess writing the subset would take the same time (~450 sec).

There is no benefit of writing a subset over using `ind.xxx` in the functions, unless you're using a small subset of rows (because columns are stored contiguously so basically accessed all when you access any element of it, even the rows you don't really need). There is absolutely no benefit if you're using a subset of columns only.

Try to run `big_univLinReg()` a second time, and you'll see that it is much faster. If you always use the same subset it should be faster all the time (after the first one).

**Comment by linoferreira** [comment]
Thank you very much for this detailed explanation. I didn't realise that the first time of accessing data would take longer than subsequent times, but it makes sense!

I've tried running `big_univLinReg()` a second time as you suggested and indeed it was much faster, taking only 14 seconds. I'm using always the same subset so this should speed things up significantly.

Thanks again for your time!
