### ISSUE TITLE
Reading existing .bk files

### ISSUE THREAD

**Issue by yavyx** [privefl/bigstatsr#141]
I'm working on a Shiny app which loads a huge meta-transcriptomics dataset (~10 GB) for exploration and analysis, and using FBMs has improved performance markedly. However, the FBMs are generated every single time the app is started (taking 7-8 minutes), so I'm trying to figure out how to read the existing .bk files on start-up instead of regenerating them every time, but I've had no success so far. I tried to follow this [vignette](https://privefl.github.io/bigstatsr/articles/read-FBM-from-file.html) but I'm under the impression this is meant for text files and not .bk files. In short, is it possible to read these .bk files into a FBM R object? I might be msising something obvious.

**Comment by privefl** [comment]
What you need to do is to use `$save()` the first time, this will create a corresponding `.rds` file, on which you can use `big_attach()` to get the FBM object in another session.

**Comment by yavyx** [comment]
It's working now, thank you!

**Comment by privefl** [comment]
That's great

Also, it would be useful to know where you have looked for this information, in case I may be able to improve the documentation a bit.

**Comment by yavyx** [comment]
I see that the `$save()` method is in the FBM [documentation](https://privefl.github.io/bigstatsr/reference/FBM-class.html), but me and the previous developer both found it difficult to understand what its purpose was until your clarification. It was a little confusing that it generates an `.rds` file that points to the `.bk` file until it finally worked. The example in the documentation for `big_attach()` was extremely useful:
```
X <- FBM(10, 10)$save()

rdsfile <- sub_bk(X$backingfile, ".rds")
X2 <- big_attach(rdsfile)

all.equal(X[], X2[])
```
However, `big_attach()` isn't included in the pkgdown [website](https://privefl.github.io/bigstatsr/reference/index.html), so I wouldn't have found it without your help. Just including this function and example on the website would help a lot, and a small vignette detailing the write/read process and the relationship between the `.rds` and `.bk` files would be even better.

**Comment by privefl** [comment]
Thanks for pointing to this.

I have now
- added the documentation of `big_attach()` to the website
- add an example of `big_attach()` in the documentation of `FBM`
- mention that you should read only once from text files (and use `big_attach()` instead) in the corresponding vignette

Hope this will make things clearer.

**Comment by minhnd212** [comment]
Hi, this assumes I have the .rds file already. But what if I only have the .bk file? Is it possible to generate a FBM from a .bk file only and if yes, could you provide the instruction or some hints on how to get the job done? Thank you

**Comment by privefl** [comment]
@minhnd212 You should be able to use `FBM()` with `create_bk = FALSE`.

**Comment by minhnd212** [comment]
Hi, thank you for your suggestion. I tried, but it didn't seem to work. I also have a few concerns with using FBM() to generate a FBM from a .bk file. Specifically:
1. I do not know nrow and ncol of the matrix currently stored in .bk file. These arguments must be specified, so which numbers should I use if I do not know the dimension of the matrix stored in .bk file 
2. So, I just used nrow = 2, ncol = 2. Following your suggestion, I used the following syntax: bm <- FBM(nrow = 2, ncol = 2, backingfile = "...", create_bk = FALSE) where "..." is the path including the name of the .bk file. I got an error that said Error: File "....bk' doesn't exist.
Could you give a hint of where I might be wrong? Thank you

**Comment by privefl** [comment]
- make sure `backingfile` is provided without the extension. The error should be quite explicit, giving you the full path it tried to find.
- if you don't know the number of rows of columns of the FBM you created previously, then you can't recreate it.

**Comment by minhnd212** [comment]
Thank you. Since I do not know the dimension of the matrix, I gave up. Still, it would be nice to be able to generate a FBM from a .bk file without the need for any additional information. 

On a side note, I tried big_read to read the .bk file, but it kept giving me an error. On another side note, in order to see how your suggestion works, I first created a .bk file, of which I know the dimension, then I tried to reverse the process using your suggestion, like I did before, except that this time I know the exact dimension, i.e. number of rows and number of columns, of the matrix and this time I provided the backingfile without its extension. The "file does not exist" error went away, but I got an error that said "Error: Inconsistency between size of backingfile and dimensions."

I suspect that something is going on inside the .bk file, rendering both big_read and FBM not be able to read it properly. Looking forward to hearing your comments on what I have done. Thank you.

**Comment by privefl** [comment]
I would need more information to be able to help you.
For example, what is the file size of the backingfile and the dimensions you provided?

**Comment by minhnd212** [comment]
I figured out what went wrong. It was because when I created the FBM object using FBM(), I specified type of elements to be "unsigned short", but when I tried to recover it using FBM() again, I did not specify the type of the elements, which are "double" by default, causing the "size-dimension mismatch" error. So, it seems that in order to recover the FBM object from the .bk file, we will need to know not only the number of rows and number of columns but also the type of the elements. Once one know all the information, one can follow your suggestion to regenerate the FBM object nicely.

Unfortunately, sometimes, we do not know any of such information except the .bk file itself. And I can see the difficulty in regenerating the FBM object from a .bk file without know the number of rows, number of columns, and type of elements. Now I understand why you recommended creating the .rds file at the same time the FBM object is created, as it is a lot easier to recover the FBM object from the .rds file than from the .bk file. Thank you.
