### ISSUE TITLE
Why the package is not on CRAN anymore?

### ISSUE THREAD

**Issue by AndreaPi** [privefl/bigstatsr#19]
Any specific reasons? Or just a matter of choice?

**Comment by privefl** [comment]
The main reason is that I had a code of conduct file and apparently you can't have that with an open source license.

The main reason I haven't push it yet to CRAN is to force people to go to GitHub because you have everything there (website, vignettes, issues, etc.).

But if someone needs this package to be on CRAN because of a dependency or anything else, just tell me and I'll do it.

**Comment by AndreaPi** [comment]
Nah, don't worry, I was just curious because I've seen something similar happen for other packages. By the way, you don't have the code of conduct file anymore, right? Or at least I couldn't find it.

**Comment by privefl** [comment]
You can find it there: https://github.com/privefl/bigstatsr/commit/5752503767ec1fbd340ea2b5000289c8268da2c4#diff-04c6e90faac2675aa89e2176d2eec7d8

It was the one recommended by the Journal of Open Source Software (JOSS).
