### ISSUE TITLE
Reason for decoupling from bigmemory?

### ISSUE THREAD

**Issue by BetweenTwoTests** [privefl/bigstatsr#53]
In your [vignette about bigstatsr & bigmemory](https://privefl.github.io/bigstatsr/articles/bigstatsr-and-bigmemory.html), you mentioned that you felt the need to remove bigmemory and implement custom, bigmemory-like FBM. Could it be possible to explain why? While the package is named "bigstatsr" with implication that this belongs in the "big" family of packages, it doesn't use bigmemory as foundation -- this is a bit confusing. It would also be great for users to understand why one might use FBM vs bigmemory.

**Comment by privefl** [comment]
Package {bigstatsr} have relied on package {bigmemory} for more than one year at the beginning.
As package {bigstatsr} is a central tool of all my thesis work, I need to add whatever feature I want whenever I want to. 

In the vignette, I explain the differences and similarities between the two packages. People are using {bigmemory} since 2009 I think. Making all those changes in {bigmemory} would have broken people's code.

If you are already familiar with package {bigmemory} and it works well for you, just keep using it. Note that if your data is filebacked, you can easily switch between a `big.matrix` and an `FBM` so that you can use functions from both packages. So, these two packages are complementary.
