### ISSUE TITLE
big_cprodMat memory issue

### ISSUE THREAD

**Issue by yzizhen** [privefl/bigstatsr#62]
I have some memory issue when running:
prod=big_cprodMat(m1, m2, ind.row=rows, ind.col=cols) 

m1 is FBM object with dim: 20000 * 10^6,  ind.row has 3000 elements and ind.col include all columns.
m2 is matrix with dim: 3000 * 20 
prod has dimension 10^6 * 20. 
During execution of the method, the memory consumption keeps growing up to 100G, although the final result is quite small, and the memory won't free up even after "gc". I am wondering if there is potential memory leak, and whether memory consumption can be managed more effectively.

**Comment by privefl** [comment]
It is normal. Your data is 150GB.
As data is accessed column-wise by blocks (when you access elements, OS also access elements near to it), accessing a subset of rows is basically the same as accessing all rows.
So, you have to access 150GB in memory here.
It will access data by blocks so that you won't run into real memory issues (i.e. when you will need more memory, OS will automatically free some for you).

**Comment by yzizhen** [comment]
Thanks for the clarification!
