### ISSUE TITLE
CRAN Solaris: caught segfault *** address cause 'invalid permissions'

### ISSUE THREAD

**Issue by privefl** [privefl/bigstatsr#89]
Part of #79.
See https://stackoverflow.com/q/59275888/6103040.

**Comment by ShotaOchi** [comment]
What is the minimal code to reproduce the segfault?

The traceback says extractVec(x$address, i) caused the segfault.
So, there are two candidates.
1. extractVec function
1. x$address

I guess this segfault is caused by undefined, unspecified or implementation-defined behavior of external pointer when creating or accessing x$address.
Can we create and access an external pointer by using Rcpp::XPtr without causing segfault on Solaris?

**Comment by privefl** [comment]
I can at least reproduce the problem by using `rhub::check_on_solaris()`.

But then, it is hard to make a *minimal* example. And I don't have access to any Solaris computer.

**Comment by privefl** [comment]
For some reason, it disappeared.

**Comment by privefl** [comment]
Still get the error if not skipping on CRAN.
And also get this error with {bigsnpr}.

**Comment by privefl** [comment]
Could it be that I can't memory-map the same data twice at the same time on Solaris?

**Comment by privefl** [comment]
Error still there, see https://cran.r-project.org/web/checks/check_results_bigsnpr.html.

**Comment by privefl** [comment]
Solaris has been removed from CRAN finally :-)
